runtime: custom
env: flex
service: api
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.8
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  name: VPC_NAME
  subnetwork_name: VPC_SUBNET_NAME